# Use a lightweight official Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Upgrade pip and install wheel before installing dependencies to avoid build issues
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir wheel


#Copy requirements and install Python dependencies 
COPY requirements-ml.txt .
COPY requirements-core.txt .
COPY requirements-azure.txt .
COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=120 --retries=5 -r requirements.txt


# Copy training code
COPY retrain.py .
COPY src/ ./src/
COPY config/ ./config/

# Set environment variables
ENV PYTHONPATH=/app

# Set the entry point to run the training script. This runs once when the container starts.
CMD ["python", "retrain.py"]