services:
  # FastAPI
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: churn-api-jaw
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=${POSTGRES_HOST}               
      - API_KEY_SECRET=${API_KEY_SECRET}
      - MLFLOW_TRACKING_URI=http://mlflow:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
        - monitor-net

  # MLFLOW SERVER
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.5.1
    container_name: mlflow
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=1
    ports:
      - "8080:8080"
    volumes:
      - ./mlflow:/mlflow
      - ./mlflow/mlruns:/mlruns
      - ./mlflow/mlartifacts:/mlartifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --host 0.0.0.0
      --port 8080
      --allowed-hosts "*"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --timeout=2 -O /dev/null http://127.0.0.1:8080/health", "||", "exit 1"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - monitor-net

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    working_dir: /app
    command: python retrain.py
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}   
      - MLFLOW_TRACKING_URI=http://mlflow:8080
    depends_on:
      mlflow:
        condition: service_started
    deploy:
      replicas: 1
    volumes:
      - .:/app
    networks:
      - monitor-net

# MLFLOW METRICS EXPORTER
  mlflow_exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: mlflow_exporter
    restart: unless-stopped
    # Exposes port 9100 for Prometheus scraping
    ports:
      - "9100:9100" 
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8080
      - EXPORTER_PORT=9100
    depends_on:
      mlflow:
        condition: service_started 
    networks:
      - monitor-net

# PROMETHEUS SERVER
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Map the configuration file (prometheus.yml)
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      # Prometheus UI runs on http://localhost:9090
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - api 
      - mlflow
      - mlflow_exporter
    networks:
      - monitor-net

  # GRAFANA VISUALIZATION 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      # Grafana UI runs on http://localhost:3000
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitor-net
      
# Define the internal network for the services to talk to each other
networks:
  monitor-net:
    driver: bridge