services:
  # FastAPI
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: churn-api-jaw
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}               
      - API_KEY_SECRET=${API_KEY_SECRET}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
        - monitor-net

  trainer:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: python retrain.py
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}   
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    deploy:
      replicas: 1   
    networks:
      - monitor-net

# PROMETHEUS SERVER
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Map the configuration file (prometheus.yml)
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      # Prometheus UI runs on http://localhost:9090
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    # DEPENDS ON 'api' to ensure target is up
    depends_on:
      - api 
    networks:
      - monitor-net

  # GRAFANA VISUALIZATION 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      # Grafana UI runs on http://localhost:3000
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitor-net
      
# Define the internal network for the services to talk to each other
networks:
  monitor-net:
    driver: bridge