aliases: []
creation_timestamp: 1764816005959
current_stage: None
description: ''
last_updated_timestamp: 1764816005959
name: nn_churn_model
run_id: 991a9002cad24efc8a311e49d228f95d
run_link: ''
source: /Users/wycliffenzomo/Documents/churn-predictor/mlflow_artifacts/456166798145918436/991a9002cad24efc8a311e49d228f95d/artifacts/model
status: READY
status_message: null
storage_location: /Users/wycliffenzomo/Documents/churn-predictor/mlflow_artifacts/456166798145918436/991a9002cad24efc8a311e49d228f95d/artifacts/model
user_id: null
version: 1
