artifact_location: /Users/wycliffenzomo/Documents/churn-predictor/mlflow_artifacts/456166798145918436
creation_time: 1764815944119
experiment_id: '456166798145918436'
last_update_time: 1764815944119
lifecycle_stage: active
name: NeuralNet_Churn_Experiment
