artifact_location: /Users/wycliffenzomo/Documents/churn-predictor/mlflow_artifacts/0
creation_time: 1764802333599
experiment_id: '0'
last_update_time: 1764802333599
lifecycle_stage: active
name: Default
