artifact_uri: /Users/wycliffenzomo/Documents/churn-predictor/mlflow_artifacts/874256967591516475/35eeef0de4dc4b41af8e3bcac0463d22/artifacts
end_time: 1764815865697
entry_point_name: ''
experiment_id: '874256967591516475'
lifecycle_stage: active
run_id: 35eeef0de4dc4b41af8e3bcac0463d22
run_name: trial_2
run_uuid: 35eeef0de4dc4b41af8e3bcac0463d22
source_name: ''
source_type: 4
source_version: ''
start_time: 1764815865687
status: 3
tags: []
user_id: wycliffenzomo
